// JUST TRYING TO REFRESH 
// let newStudents = ['David', 'Yongo', 'Emmanuel', 'Christian']
// console.log(newStudents)

// for (let i = 0; i < newStudents.length; i++){
//     console.log(newStudents[i])
// }

// newStudents.forEach(student =>{
//         console.log(student)
// });

// let i = 0;
// while (i < newStudents.length) {
//     console.log(newStudents[i])
//     i++
// };

// const scores = [50, 25, 35, 20, 41, 7, 75, 81, 1, 19, 90, 20, 65, 76, 90, 8]

// let score = window.prompt('Enter score')
// if (score >= 70 || 'A') {
//     console.log('You passed sir')
// } else if (score >= 60 || 'B') {
//     console.log('You did your best sir')
// } else if (score >= 50 || 'C') {
//     console.log('You can do better sir')
// } else if (score >= 45 || 'D') {
//     console.log('At least you tried sir')
// } else if (score <= 20 || 'E') {
//     console.log('You failed')
// } else {
//     console.log('Please input your score here :')
// }

// const username = prompt('Enter grade')
// switch (username) {
//     case 'A':
//         console.log('Excellent work boy')
//         break;
//     case 'B':
//         console.log('Good work')
//         break;
//     case 'C':
//         console.log('You can do better')
//         break;
//     case 'D':
//         console.log('well you can try again')
//         break;
//     default:
//         console.log('Sadly you failed')
// }

// let r = Math.random()*1000;
// let area = Math.PI * (r ** 2);
// let round = Math.round(area);
// let ceil = Math.ceil(area);
// let floor = Math.floor(area);

// console.log(area);
// console.log(round);
// console.log(ceil);
// console.log(floor);

// let firstName = 'David'
// let lastName = 'Yongo'

// const fullName = firstName + ' ' + lastName

// FUNCTIONS
// function logConsole() {
//     console.log('We are about to begin functions')
// };
// logConsole()

// const arrow = () => {
//     console.log('This is an arrow function');
// }
// arrow()


// let a = 5
// let b = 6

// const sum = () => {
//     let area = a * b 
//     console.log(area)
// }
// sum()

// let goods = 50
// let amount = 5 
// const totalAll = () => {
//     let All = goods + amount
//     console.log(All)
// }
// totalAll()

// function Sum() {
//     let firstSum = 30 + 30 
//     console.log(firstSum)
// }
// Sum();

// window.prompt('What is your age')
// function verifiyAge () {
//     let Age = 30;
//     if (Age >= 10) {
//         console.log('You have to be older');
//     } else if (Age <= 10) {
//         console.log('You are not of age');
//     } else if (Age >= 20) {
//         console.log('Yes you are of age');
//     }
// };
// verifiyAge()

// const  Detials = {
//     Fname: 'Davd',
//     Lname: 'Yongo',
//     Age: 23,
//     email: 'DavidYongo9@gmail.com',
//     phone: [
//         {
//             type: 'Home',
//             phone: '09053647455'
//         },
//         {
//             type: 'Mobile',
//             phone: '09073r63724'
//         }
//     ],

// }
// console.log(Detials);

// function fullDetials() {
//     let YourFull = `Your name is ${Detials.Fname} ${Detials.Lname} and you are ${Detials.Age} here is your email address ${Detials.email}`;
//     console.log(YourFull)
// }
// fullDetials();


// function fullDetials (Detials){
//     let YourDetials = `Your name is ${Fname} ${Lname} you are ${age} years of age
//     Here is your email address ${email} and thses are your phone number ${phone}`
//     return YourDetials;
//     let Profile = YourDetials;
//     console.log(Detials);
// }



